---
- name: Git shell install Debian
  shell: apt install -y git
  register: out
  ignore_errors: yes
#- name: Message from Debian
#  debug: 
#    msg: "{{ out.stdout_lines }}"
- name: Output of "apt install git"
  set_fact:
    d_var: "{{ out.stdout_lines }}"
#- name: Print list from Debian
#  debug:
#    msg: "{{ d_var[0] }}"
- name: Variable for fact
  set_fact:
    value: "{{ sudo_var if ( d_var[0] == ok_debian) else nosudo_var }}"
- name: Print Permissions
  debug:
    msg: "{{ value }}"
- name: Remove git on Debian if it installed
  shell: apt remove -y git
  ignore_errors: yes
#- name: Install Nginx on Debian family
#  apt:
#    name: git
#    state: present
#    update_cache: yes
#- name: Nginx. Enable and start service on Debian family
#  service:
#    name: nginx
#    state: started
#    enabled: yes
