---
- name: Git shell install RedHat
  shell: yum -y install git
  register: out
  ignore_errors: yes
#- name: Message from RedHat
#  debug: 
#    msg: "{{ out.stdout_lines }}"
- set_fact:
    r_var: "{{ out.stdout_lines }}"
#- name: Print element of list
#  debug:
#    msg: "{{ r_var|length }}"
- set_fact:
    value: "{{ sudo_var if ( r_var|length > 1) else nosudo_var }}"
- name: Print Permissions
  debug:
    msg: "{{ value }}"
- name: Remove Git on RedHat family if it installed
  shell: yum remove git
